### ISSUE TITLE
Cannot read property of 'GitHub' of undefined

### ISSUE THREAD

**Issue by rednax1994** [yubozhao/meteor-link-accounts#64]
When I install the package and start using it, I get: Uncaught TypeError: Cannot read property 'Github' of undefined. I'm not sure where this could be going wrong.

**Comment by yinnovationlab** [comment]
Similar problem "Cannot read property 'Google' of undefined". My code was working when I checked last time.

**Comment by vladgolubev** [comment]
@yinnovationlab good news, version `1.2.10` fixes this

**Comment by harveysanders** [comment]
I still had this problem in `1.2.1` for Meteor `1.4.4.2` I believe it's due to Meteor using the `github-oauth` package instead of `github`, similiar to this issue: https://github.com/percolatestudio/meteor-google-api/issues/40#issuecomment-280662638

I've fixed In my project by referencing the new package. I'll put in a PR if you'd like to check it out, but I haven't checked for older Meteor versions.

**Comment by elmarti** [comment]
I had this issue, got round it by running ```meteor add github```

**Comment by elmarti** [comment]
Not sure why this was closed, but I've got it to work by importing Github via es6 instead of using `Package.github.Github`. I can create a PR with refactors for all of the services and I plan to add Bitbucket and Gitlab if those are of interest
